services:
  # Serverpod application server
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: watchwise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5DSV-jq2bDFrY7oUFXvksaRamSiyJ8nO
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: hRTeXLSLqSx0VPI0IL0b5nUbKKDntbfq
      TMDB_API_KEY: 466fd9ba21e369cd51e7743d32b7833f
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL with pgvector
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: watchwise
      POSTGRES_PASSWORD: "5DSV-jq2bDFrY7oUFXvksaRamSiyJ8nO"
    volumes:
      - watchwise_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis cache
  redis:
    image: redis:6.2.6
    command: redis-server --requirepass "hRTeXLSLqSx0VPI0IL0b5nUbKKDntbfq"
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "hRTeXLSLqSx0VPI0IL0b5nUbKKDntbfq", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  watchwise_data:
